#!/usr/bin/env python3
"""Write a unified Socratic learning note.

Always strips any prior Socratic summary and session blocks from the note,
then writes a single unified block. Safe for first use (nothing to strip)
and for merging multiple quiz sessions into one coherent note.
"""

from __future__ import annotations

import argparse
import datetime as dt
import re
from pathlib import Path


PROVENANCE_URL = "https://github.com/PinkR1ver/socratic-learning"

# Headings that mark Socratic content to strip in merge mode.
SOCRATIC_HEADING_PATTERN = re.compile(
    r"^## Socratic Learning (Summary|Session)\b",
)


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8").strip()


def build_block(summary: str, qa: str, title: str, date: str) -> str:
    return f"""## {title} - {date}

{summary}

<details class="socratic-learning-session">
<summary>QA session generated by PinkR1ver/socratic-learning</summary>

Generated by [PinkR1ver/socratic-learning]({PROVENANCE_URL}).

{qa}

</details>
"""


def strip_socratic_sections(text: str) -> str:
    """Remove all Socratic summary and session sections from the note body.

    A Socratic section starts with a ``## Socratic Learning Summary`` or
    ``## Socratic Learning Session`` heading and ends just before the next
    top-level or second-level heading, or at EOF.  We also clean up trailing
    blank lines left behind after removal.
    """
    lines = text.splitlines(keepends=True)
    result: list[str] = []
    in_socratic = False
    i = 0

    while i < len(lines):
        line = lines[i]
        stripped = line.lstrip()

        if stripped.startswith("## ") and SOCRATIC_HEADING_PATTERN.match(stripped):
            # Entering a Socratic section — skip this line and everything
            # until the next heading at the same or higher level.
            in_socratic = True
            i += 1
            continue

        if in_socratic:
            # A new heading (## or #) ends the Socratic section.
            if stripped.startswith("## ") or stripped.startswith("# "):
                in_socratic = False
                # Continue to process this heading line normally.
                continue
            # Still inside the Socratic section — skip.
            i += 1
            continue

        result.append(line)
        i += 1

    # Collapse runs of blank lines left by removed sections (max 2 consecutive).
    cleaned: list[str] = []
    blank_run = 0
    for line in result:
        if line.strip() == "":
            blank_run += 1
            if blank_run <= 2:
                cleaned.append(line)
        else:
            blank_run = 0
            cleaned.append(line)

    # Strip leading/trailing blank lines.
    while cleaned and cleaned[0].strip() == "":
        cleaned.pop(0)
    while cleaned and cleaned[-1].strip() == "":
        cleaned.pop(-1)

    return "".join(cleaned)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Write a unified Socratic learning note."
    )
    parser.add_argument("note", type=Path, help="Target Markdown note")
    parser.add_argument("--summary-file", required=True, type=Path)
    parser.add_argument("--qa-file", required=True, type=Path)
    parser.add_argument("--title", default="Socratic Learning Session")
    parser.add_argument("--date", default=dt.date.today().isoformat())
    args = parser.parse_args()

    if not args.note.exists():
        raise SystemExit(f"Target note does not exist: {args.note}")
    if args.note.suffix.lower() != ".md":
        raise SystemExit(f"Target note is not Markdown: {args.note}")

    original = args.note.read_text(encoding="utf-8")
    original = strip_socratic_sections(original)

    summary = read_text(args.summary_file)
    qa = read_text(args.qa_file)
    block = build_block(summary, qa, args.title, args.date)

    separator = "\n\n" if original.strip() else ""
    args.note.write_text(original.rstrip() + separator + block + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
